# Generated by Django 4.2.30 on 2026-06-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='场景标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='场景描述/背景介绍')),
                ('category', models.CharField(choices=[('food', '餐饮美食'), ('travel', '交通出行'), ('shopping', '购物血拼'), ('daily', '日常生活'), ('business', '商务职场')], default='daily', max_length=20, verbose_name='场景分类')),
                ('level', models.CharField(choices=[('N5', 'N5 (入门)'), ('N4', 'N4 (基础)'), ('N3', 'N3 (进阶)'), ('N2', 'N2 (中高级)'), ('N1', 'N1 (高级)')], default='N5', max_length=5, verbose_name='难度等级')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学习场景',
                'verbose_name_plural': '学习场景',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', '角色A (如：顾客/提问者)'), ('B', '角色B (如：店员/回答者)')], default='A', max_length=1, verbose_name='说话角色')),
                ('japanese_text', models.CharField(max_length=255, verbose_name='日文原文')),
                ('kana_text', models.CharField(blank=True, default='', max_length=255, verbose_name='平假名注音 (Furigana)')),
                ('romaji_text', models.CharField(blank=True, default='', max_length=255, verbose_name='罗马音')),
                ('chinese_text', models.CharField(max_length=255, verbose_name='中文翻译')),
                ('audio_url', models.URLField(blank=True, default='', max_length=500, verbose_name='发音音频URL')),
                ('vocabulary', models.JSONField(blank=True, default=list, verbose_name='核心词汇/语法点')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='对话顺序')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='scenes.scene', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '对话句子',
                'verbose_name_plural': '对话句子',
                'ordering': ['scene', 'order'],
            },
        ),
    ]
