# Generated by Django 4.2.30 on 2026-06-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_marked', models.BooleanField(default=False, verbose_name='是否标记为难点')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to='scenes.dialogue', verbose_name='对话')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to='scenes.scene', verbose_name='场景')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'dialogue')},
            },
        ),
    ]
