"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta  # ⬅️ 新增：用于 JWT 过期时间配置
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_6$t4k1)^1lu296f=yarnm^0&mb$4u%68*ai29+ri61&t$37e!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ⬇️ 新增：第三方库
    'rest_framework',       # Django REST Framework
    'corsheaders',          # 处理跨域请求
    
    # ⬇️ 新增：本地应用 (确保你已经运行了 python manage.py startapp users)
    'users',
    'scenes', # ⬅️ 新增
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ⬅️ 新增：必须放在最前面！拦截跨域请求
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# ⬇️ 修改：后台管理界面使用中文，时区设为东京（契合日语学习项目）
LANGUAGE_CODE = 'zh-hans'  
TIME_ZONE = 'Asia/Tokyo'   

USE_I18N = True
USE_TZ = True  # 保持 True，确保数据库存储 UTC 时间，展示时自动转换


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================================================================
# 👇👇👇 以下为前后端分离专属核心配置 (新增部分) 👇👇👇
# =====================================================================

# ================= 7. 自定义用户模型 =================
# ⚠️ 极其重要：必须在第一次 migrate 之前配置，指向我们自己写的 User 模型
AUTH_USER_MODEL = 'users.User'


# ================= 8. CORS 跨域配置 =================
# 允许你的前端 HTML 文件（通过 Live Server 或本地直接打开）访问后端
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5500",  # VS Code Live Server 默认端口
    "http://127.0.0.1:5500",
    "http://localhost:8080",
    "http://localhost:3000",  # React/Next.js 默认端口
    "http://localhost:5173",  # Vite 默认端口
    "http://127.0.0.1:8000",  # 如果前端和后端跑在同一个端口（不推荐但兼容）
    "http://localhost:8001",  # 后端 Django 服务端口
    "http://127.0.0.1:8001",
]

# 允许前端携带 Cookie（虽然 JWT 主要用 Header，但备用开启）
CORS_ALLOW_CREDENTIALS = True 

# 修复 macOS Safari 浏览器的预检请求 (OPTIONS) 缓存问题
CORS_PREFLIGHT_MAX_AGE = 86400 


# ================= 9. CSRF 配置 (针对前后端分离) =================
# 前后端分离通常使用 JWT 放在 Header 中，不依赖 Cookie，因此可以放宽 CSRF 限制
# 如果你前端使用 127.0.0.1，这里也要加上，防止 Safari 报错
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost:5500',
    'http://127.0.0.1:5500',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
]


# ================= 10. Django REST Framework 全局配置 =================
REST_FRAMEWORK = {
    # 默认认证方式：JWT
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 默认权限：必须登录才能访问（AllowAny 需在具体 View 中单独指定）
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 统一时间返回格式，避免前端解析 ISO 8601 麻烦
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    # 默认分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# ================= 11. Simple JWT 配置 =================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),   # Access Token 2小时过期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Refresh Token 7天过期
    'ROTATE_REFRESH_TOKENS': True,                 # 刷新时轮换 Token（更安全）
    'BLACKLIST_AFTER_ROTATION': True,              # 轮换后将旧 Token 加入黑名单
    'AUTH_HEADER_TYPES': ('Bearer',),              # 请求头格式：Authorization: Bearer <token>
}